# This is a basic workflow to help you get started with Actions
name: Publish Static Version on Github Pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
 push:
   branches: [ main ]
 pull_request:
   branches: [ main ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    env:
      NOTION_API: ${{ secrets.NOTION_API }}
      NOTION_DATABASE: ${{ secrets.NOTION_DATABASE }}
      BASE_URL: ${{ secrets.BASE_URL }}
      
    strategy:
      fail-fast: true
      matrix:
        php-versions: ['7.4']

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

  # http://github.com/shivammathur/setup-php (community)
      - name: Setup PHP, extensions and composer with shivammathur/setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, xml, ctype, iconv, intl, pdo, pdo_mysql, dom, filter, iconv, json, mb
        env:
          update: true
      
          
      - name : Composer Install
        run: composer install
        
      - name : Generate Static Dump
        run: php bin/console dump-static-site
        
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
